#!/usr/bin/env bash

# =============================================================================
# IsaacLab Development Container Manager
# =============================================================================
#
# Usage:
#   ./docker/run.sh build   — Build (or rebuild) the Docker image
#   ./docker/run.sh start   — Create and start the container
#                             (X11 forwarding + SSH agent + workspace setup)
#   ./docker/run.sh enter   — Open an interactive bash shell in the container
#   ./docker/run.sh stop    — Stop and remove the container
#   ./docker/run.sh status  — Show container status
#   ./docker/run.sh help    — Print this help message
#
# Features:
#   • X11 forwarding  — GUI / headless rendering via host display
#   • SSH agent fwd   — enables git clone / push from inside the container
#   • Host file share — source/, scripts/, docs/, tools/ are bind-mounted
#   • Auto-setup      — clones & installs whole_body_tracking on first start
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ISAACLAB_DIR="$(dirname "$SCRIPT_DIR")"

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO] ${NC}$*"; }
warn()    { echo -e "${YELLOW}[WARN] ${NC}$*"; }
error()   { echo -e "${RED}[ERR]  ${NC}$*" >&2; }
section() { echo -e "\n${CYAN}${BOLD}==> $* ${NC}"; }

# ---------------------------------------------------------------------------
# Config — loaded from .env.base
# ---------------------------------------------------------------------------
ENV_FILE="$SCRIPT_DIR/.env.base"
if [ ! -f "$ENV_FILE" ]; then
    error "Missing env file: $ENV_FILE"
    exit 1
fi
set -a; source "$ENV_FILE"; set +a

COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yaml"
OVERRIDE_FILE="$SCRIPT_DIR/.docker-compose.dev.override.yaml"
PROFILE="base"
CONTAINER_NAME="isaac-lab-base"

# ---------------------------------------------------------------------------
# Cleanup the temporary override on exit
# ---------------------------------------------------------------------------
cleanup() { rm -f "$OVERRIDE_FILE"; }
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Helper: generate a docker-compose override for X11 + SSH agent
# ---------------------------------------------------------------------------
generate_override() {
    local has_x11=false has_ssh=false

    [ -n "${DISPLAY:-}" ] && has_x11=true
    [ -n "${SSH_AUTH_SOCK:-}" ] && [ -S "${SSH_AUTH_SOCK}" ] && has_ssh=true

    {
        echo "# Auto-generated by run.sh — do not edit"
        echo "services:"
        echo "  isaac-lab-base:"

        # ---- environment ----
        echo "    environment:"
        if $has_x11; then
            echo "      - DISPLAY=${DISPLAY}"
            echo "      - QT_X11_NO_MITSHM=1"
            echo "      - TERM=${TERM:-xterm-256color}"
        fi
        if $has_ssh; then
            echo "      - SSH_AUTH_SOCK=/ssh-agent"
        fi

        # ---- volumes ----
        echo "    volumes:"
        if $has_x11; then
            echo "      - type: bind"
            echo "        source: /tmp/.X11-unix"
            echo "        target: /tmp/.X11-unix"
            echo "      - type: bind"
            echo "        source: /etc/localtime"
            echo "        target: /etc/localtime"
            echo "        read_only: true"
        fi
        if $has_ssh; then
            echo "      - type: bind"
            echo "        source: ${SSH_AUTH_SOCK}"
            echo "        target: /ssh-agent"
        fi

    } > "$OVERRIDE_FILE"

    $has_x11 && info  "X11 forwarding  : enabled  (DISPLAY=${DISPLAY})" \
             || warn  "X11 forwarding  : disabled (DISPLAY not set)"
    $has_ssh && info  "SSH agent fwd   : enabled  (socket=${SSH_AUTH_SOCK})" \
             || warn  "SSH agent fwd   : disabled (SSH_AUTH_SOCK not set / not a socket)"
}

# ---------------------------------------------------------------------------
# Helper: is the container running?
# ---------------------------------------------------------------------------
is_running() {
    docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${CONTAINER_NAME}$"
}

# ===========================================================================
# Commands
# ===========================================================================

cmd_build() {
    section "Building Isaac Lab Docker image  (profile: ${PROFILE})"
    docker compose \
        -f "$COMPOSE_FILE" \
        --profile "$PROFILE" \
        --env-file "$ENV_FILE" \
        build
    info "Build complete."
}

cmd_start() {
    section "Starting Isaac Lab container  (${CONTAINER_NAME})"

    # X11: allow local docker connections
    if [ -n "${DISPLAY:-}" ]; then
        xhost +local:docker &>/dev/null \
            && info "xhost: granted docker access to X11 display" \
            || warn "xhost failed — X11 GUI may not work (try: xhost +local:docker)"
    fi

    # Generate dynamic compose override
    generate_override

    info "Launching container in detached mode..."
    docker compose \
        -f "$COMPOSE_FILE" \
        -f "$OVERRIDE_FILE" \
        --profile "$PROFILE" \
        --env-file "$ENV_FILE" \
        up -d

    # Run workspace initialisation inside the container
    section "Running workspace setup (whole_body_tracking)"
    docker exec -i "$CONTAINER_NAME" bash < "$SCRIPT_DIR/setup_workspace.sh"

    section "Container ready"
    info "Use './docker/run.sh enter' to open a shell."
    info "Use './docker/run.sh stop'  to shut it down."
}

cmd_enter() {
    if ! is_running; then
        error "Container '${CONTAINER_NAME}' is not running."
        echo "  Start it with:  ./docker/run.sh start"
        exit 1
    fi
    section "Entering container  (${CONTAINER_NAME})"
    docker exec -it "$CONTAINER_NAME" bash
}

cmd_stop() {
    section "Stopping container  (${CONTAINER_NAME})"
    docker compose \
        -f "$COMPOSE_FILE" \
        --profile "$PROFILE" \
        --env-file "$ENV_FILE" \
        down
    info "Container stopped and removed."
}

cmd_status() {
    section "Container status"
    if is_running; then
        echo -e "  ${GREEN}● RUNNING${NC}  —  ${CONTAINER_NAME}"
        docker ps --filter "name=${CONTAINER_NAME}" --format \
            "  Image: {{.Image}}\n  Status: {{.Status}}\n  Ports: {{.Ports}}"
    else
        echo -e "  ${RED}○ STOPPED${NC}  —  ${CONTAINER_NAME}"
    fi
}

cmd_help() {
    echo ""
    echo -e "${CYAN}${BOLD}IsaacLab Dev Container Manager${NC}"
    echo ""
    echo -e "  ${BOLD}Usage:${NC}  $(basename "$0") <command>"
    echo ""
    echo -e "  ${GREEN}build${NC}   Build (or rebuild) the Docker image"
    echo -e "  ${GREEN}start${NC}   Start the container with X11 + SSH agent + auto workspace setup"
    echo -e "  ${GREEN}enter${NC}   Open an interactive bash shell inside the running container"
    echo -e "  ${GREEN}stop${NC}    Stop and remove the container"
    echo -e "  ${GREEN}status${NC}  Show whether the container is running"
    echo -e "  ${GREEN}help${NC}    Print this help message"
    echo ""
    echo -e "  ${BOLD}File sharing${NC} (host ↔ container, always live):"
    echo "    source/   →  \${DOCKER_ISAACLAB_PATH}/source"
    echo "    scripts/  →  \${DOCKER_ISAACLAB_PATH}/scripts"
    echo "    docs/     →  \${DOCKER_ISAACLAB_PATH}/docs"
    echo "    tools/    →  \${DOCKER_ISAACLAB_PATH}/tools"
    echo ""
    echo -e "  ${BOLD}Auto workspace setup${NC}:"
    echo "    On first start, the container clones and installs:"
    echo "    git@github.com:ValenQiu/whole_body_tracking.git"
    echo "    → source/whole_body_tracking/  (persists on the host via bind mount)"
    echo ""
}

# ===========================================================================
# Main
# ===========================================================================
case "${1:-help}" in
    build)  cmd_build  ;;
    start)  cmd_start  ;;
    enter)  cmd_enter  ;;
    stop)   cmd_stop   ;;
    status) cmd_status ;;
    help|--help|-h) cmd_help ;;
    *)
        error "Unknown command: '$1'"
        cmd_help
        exit 1
        ;;
esac
