#!/usr/bin/env bash

# =============================================================================
# IsaacLab Development Container Manager
# =============================================================================
#
# A thin wrapper around docker/container.py that adds:
#   1. SSH agent forwarding — mounts the host SSH socket so git operations
#      inside the container use your host SSH keys.
#   2. Auto workspace setup — on every "start", clones and installs the
#      whole_body_tracking repo if it isn't already present.
#
# All X11 forwarding is handled by the existing container.py / x11.yaml
# infrastructure (xauth + MIT-MAGIC-COOKIE), which this script delegates to.
#
# Usage:
#   ./docker/run.sh build   — Build (or rebuild) the Docker image
#   ./docker/run.sh start   — Start the container (SSH agent + workspace setup)
#   ./docker/run.sh enter   — Open an interactive bash shell in the container
#   ./docker/run.sh stop    — Stop and remove the container
#   ./docker/run.sh help    — Show this message
#
# All other arguments (e.g. --files, --env-files, profile) are forwarded
# transparently to container.py.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO] ${NC}$*"; }
warn()    { echo -e "${YELLOW}[WARN] ${NC}$*"; }
error()   { echo -e "${RED}[ERR]  ${NC}$*" >&2; }
section() { echo -e "\n${CYAN}${BOLD}==> $*${NC}"; }

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
CONTAINER_PY="$SCRIPT_DIR/container.py"
SSH_OVERRIDE="$SCRIPT_DIR/.docker-compose.ssh-agent.yaml"
CONTAINER_NAME="isaac-lab-base"

# Load DOCKER_ISAACLAB_PATH from .env.base for use in exec commands
ENV_FILE="$SCRIPT_DIR/.env.base"
set -a; source "$ENV_FILE"; set +a

# ---------------------------------------------------------------------------
# Generate a temporary docker-compose override for SSH agent forwarding.
# The file is cleaned up on exit.
# ---------------------------------------------------------------------------
cleanup() { rm -f "$SSH_OVERRIDE"; }
trap cleanup EXIT

generate_ssh_override() {
    if [ -z "${SSH_AUTH_SOCK:-}" ] || [ ! -S "$SSH_AUTH_SOCK" ]; then
        warn "SSH_AUTH_SOCK not set or not a socket — SSH agent forwarding disabled"
        warn "  git clone / push via SSH inside the container may require manual key setup"
        return
    fi

    info "SSH agent forwarding enabled  (socket: $SSH_AUTH_SOCK)"
    {
        echo "# Auto-generated by run.sh — do not commit"
        echo "services:"
        echo "  isaac-lab-base:"
        echo "    environment:"
        echo "      - SSH_AUTH_SOCK=/ssh-agent"
        echo "    volumes:"
        echo "      - type: bind"
        echo "        source: ${SSH_AUTH_SOCK}"
        echo "        target: /ssh-agent"
    } > "$SSH_OVERRIDE"
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

cmd_build() {
    section "Building Isaac Lab Docker image"
    python3 "$CONTAINER_PY" start "$@"
    # container.py start builds if needed; stop immediately after build-only pass
    # Alternatively: use docker compose build directly
    info "Tip: 'start' also builds if the image is missing. Use 'stop' to tear down after."
}

cmd_start() {
    section "Starting Isaac Lab container"

    generate_ssh_override

    # Build the extra --files argument for container.py if SSH override was created
    EXTRA_ARGS=()
    if [ -f "$SSH_OVERRIDE" ]; then
        EXTRA_ARGS+=(--files "$SSH_OVERRIDE")
    fi

    # Delegate to container.py (handles X11, volumes, profiles, etc.)
    # Use || true so a non-zero exit (e.g. already-running container) doesn't
    # abort the script before workspace setup runs.
    python3 "$CONTAINER_PY" start "${EXTRA_ARGS[@]}" "$@" || true

    # Run workspace initialisation inside the running container
    section "Running workspace setup (whole_body_tracking)"
    _run_setup
}

cmd_enter() {
    # Always run setup before entering so that even if the container was started
    # via container.py directly, deps are correct.
    section "Running workspace setup before entering"
    _run_setup

    section "Entering container  ($CONTAINER_NAME)"
    python3 "$CONTAINER_PY" enter "$@"
}

# ---------------------------------------------------------------------------
# Shared: run setup_workspace.sh inside the container
# ---------------------------------------------------------------------------
_run_setup() {
    if ! docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${CONTAINER_NAME}$"; then
        warn "Container '${CONTAINER_NAME}' is not running — skipping workspace setup"
        return
    fi
    docker exec -i "$CONTAINER_NAME" bash < "$SCRIPT_DIR/setup_workspace.sh" \
        && info "Workspace setup complete." \
        || warn "Workspace setup returned errors — check output above"
}

cmd_stop() {
    section "Stopping container  ($CONTAINER_NAME)"
    python3 "$CONTAINER_PY" stop "$@"
}

cmd_help() {
    echo ""
    echo -e "${CYAN}${BOLD}IsaacLab Dev Container Manager${NC}  (wraps container.py)"
    echo ""
    echo -e "  ${BOLD}Usage:${NC}  $(basename "$0") <command> [container.py options]"
    echo ""
    echo -e "  ${GREEN}build${NC}   Build (or rebuild) the Docker image"
    echo -e "  ${GREEN}start${NC}   Start the container + SSH agent forwarding + workspace auto-setup"
    echo -e "  ${GREEN}enter${NC}   Open an interactive bash shell in the running container"
    echo -e "  ${GREEN}stop${NC}    Stop and remove the container"
    echo -e "  ${GREEN}help${NC}    Print this help message"
    echo ""
    echo -e "  ${BOLD}Extras added on top of container.py:${NC}"
    echo "    • SSH agent forwarding via \$SSH_AUTH_SOCK (enables git SSH inside container)"
    echo "    • Auto-clones git@github.com:ValenQiu/whole_body_tracking.git into"
    echo "      source/whole_body_tracking/ on first start (persists via bind mount)"
    echo "    • Auto-runs pip install -e on every start to restore editable install"
    echo ""
    echo -e "  ${BOLD}X11 forwarding${NC} is managed by container.py / x11.yaml (unchanged)."
    echo ""
    echo -e "  Extra container.py flags can be appended, e.g.:"
    echo "    ./docker/run.sh start --env-files .env.myoverride"
    echo "    ./docker/run.sh enter ros2"
    echo ""
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
COMMAND="${1:-help}"
shift || true   # consume the command; remaining args passed to container.py

case "$COMMAND" in
    build)  cmd_build  "$@" ;;
    start)  cmd_start  "$@" ;;
    enter)  cmd_enter  "$@" ;;
    stop)   cmd_stop   "$@" ;;
    help|--help|-h) cmd_help ;;
    *)
        error "Unknown command: '$COMMAND'"
        cmd_help
        exit 1
        ;;
esac
